### PR TITLE
change location of form.utils import for django 1.9

### PR DESCRIPTION
**Pull request by stenius**

### CODE REVIEW

**Comment by goinnn** [comment]
Please could you do a PR backward compatible? (try/ except ImportError)

**Comment by stenius** [comment]
Goinnn: just added a new comment onto this PR with your requested changes, not sure if you got a notification from the repo commit.  Thanks for accepting my PR if no other problems.

**Comment by goinnn** [comment]
@stenius Thanks! I will try to add Django 1.9 compability soon

**Comment by goinnn** [comment]
https://github.com/django-inplaceedit/django-inplaceedit-extra-fields/commit/2317206db6b43cb67fad76c21b033233cfa20535

https://github.com/django-inplaceedit/django-inplaceedit-extra-fields/commit/326861bb3b0cb1409f719b33babebf8d3e6191db

**Pull request closed without merging**
